Ajay Giri
Roll No. : 13204

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/AJAY/Downloads/train_and_test2.csv")

In [6]:
df.head(5)

,team1,team2,match_date,toss_winner,toss_decision,winner,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over
0,Mumbai Indians,Chennai Super Kings,2023-04-01,Mumbai Indians,bat,Mumbai Indians,16,1,League,runs,15,160,20,N
1,Chennai Super Kings,Mumbai Indians,2023-04-02,Chennai Super Kings,field,Chennai Super Kings,16,2,League,wickets,6,175,20,N
2,Royal Challengers Bangalore,Kolkata Knight Riders,2023-04-03,Royal Challengers Bangalore,bat,Kolkata Knight Riders,16,3,League,runs,20,180,20,N
3,Kolkata Knight Riders,Royal Challengers Bangalore,2023-04-04,Kolkata Knight Riders,field,Royal Challengers Bangalore,16,4,League,wickets,5,150,20,N
4,Rajasthan Royals,Punjab Kings,2023-04-05,Rajasthan Royals,bat,Punjab Kings,16,5,League,runs,10,165,20,N

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   team1          20 non-null     object
 1   team2          20 non-null     object
 2   match_date     20 non-null     object
 3   toss_winner    20 non-null     object
 4   toss_decision  20 non-null     object
 5   winner         20 non-null     object
 6   season         20 non-null     int64
 7   match_number   20 non-null     int64
 8   match_type     20 non-null     object
 9   result         20 non-null     object
 10  result_margin  20 non-null     int64
 11  target_runs    20 non-null     int64
 12  target_overs   20 non-null     int64
 13  super_over     20 non-null     object
dtypes: int64(5), object(9)
memory usage: 2.3+ KB

In [8]:
df.describe()

       season  match_number  result_margin  target_runs  target_overs
count    20.0      20.00000      20.000000    20.000000          20.0
mean     16.0      10.50000      10.900000   171.250000          20.0
std       0.0       5.91608       6.608607    16.357438           0.0
min      16.0       1.00000       1.000000   145.000000          20.0
25%      16.0       5.75000       5.750000   159.750000          20.0
50%      16.0      10.50000      10.500000   169.000000          20.0
75%      16.0      15.25000      15.250000   180.250000          20.0
max      16.0      20.00000      25.000000   210.000000          20.0

In [9]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [10]:
df.shape

(20, 14)

In [11]:
df.columns.names

FrozenList([None])

In [12]:
df.columns.values

array(['team1', 'team2', 'match_date', 'toss_winner', 'toss_decision',
       'winner', 'season', 'match_number', 'match_type', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over'],
      dtype=object)

In [13]:
df.dtypes

team1            object
team2            object
match_date       object
toss_winner      object
toss_decision    object
winner           object
season            int64
match_number      int64
match_type       object
result           object
result_margin     int64
target_runs       int64
target_overs      int64
super_over       object
dtype: object

In [14]:
df.shape

(20, 14)

In [15]:
df.columns

Index(['team1', 'team2', 'match_date', 'toss_winner', 'toss_decision',
       'winner', 'season', 'match_number', 'match_type', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over'],
      dtype='object')

In [18]:
df.iloc[15]

team1              Sunrisers Hyderabad
team2            Kolkata Knight Riders
match_date                  2023-04-16
toss_winner        Sunrisers Hyderabad
toss_decision                    field
winner           Kolkata Knight Riders
season                              16
match_number                        16
match_type                      League
result                         wickets
result_margin                        2
target_runs                        162
target_overs                        20
super_over                           N
Name: 15, dtype: object